### ISSUE TITLE
Organization renaming

### ISSUE THREAD

**Issue by dievri** [stellarbeat/js-stellarbeat-backend#17]
If organization was renamed, how it is possible to delete original organization from database, so it will not show up on frontend?

**Comment by pieterjan84** [comment]
Hi, organization archival will be handled in the future. What organization is it? I will clean it up manually for the time being and leave this issue open until it is automated.

**Comment by dievri** [comment]
@pieterjan84, its on my local network. How can I do it on my own?

**Comment by pieterjan84** [comment]
Every organization has one or more organization_snapshots. There is only one active snapshot at a time that you can identify through the end_date column. If you want to archive an organization, stop your crawling/update_nodes process and set the end_date of its active snapshot to a date in the past.

**Comment by dievri** [comment]
@pieterjan84, great, thanks

**Comment by pieterjan84** [comment]
Fixed in code. If you plan to upgrade to 0.3.1, checkout changelog.md
