### ISSUE TITLE
Error on yarn seed-db: Command failed with exit code 255

### ISSUE THREAD

**Issue by vikujangid** [stellarbeat/js-stellarbeat-backend#44]
I'm following all the steps and getting error on 
`yarn seed-db `

The error is:

> ubuntu@ip-172:~/js-stellarbeat-backend$ yarn seed-db
> yarn run v1.22.19
> $ node lib/network/infrastructure/cli/seed-db
> Usage: /home/ubuntu/js-stellarbeat-backend/lib/network/infrastructure/cli/seed-db.js nodes.json
> error Command failed with exit code 255.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

My NodeJs version is 16.16.0
OS Ubuntu 22

**Comment by pieterjan84** [comment]
You needed to add a nodes.json file parameter with seed nodes.

However Seed db is no longer necessary. 
You can supply IP-addresses of nodes (that you can look up on https://stellarbeat.io) in the KNOWN_PEERS environment variable  (.env) to bootstrap the crawling.
